INSERT INTO job_applied(
    job_id,
    application_sent_date,
    custom_resume,
    resume_file_name,
    cover_letter_sent,
    cover_letter_file_name,
    status)
VALUES (1,
        '2024-02-01',
        true,
        'resume_01.pdf',
        true,
        'cover_letter_01.pdf',
        'Submitted'),
        (2,
        '2024-02-05',
        false,
        NULL,
        false,
        'cover_letter_02.pdf',
        'Submitted'),
        (3,
        '2024-02-10',
        true,
        'resume_03.pdf',
        true,
        'cover_letter_03.pdf',
        'Under Review'),
        (4,
        '2024-02-15',
        false,
        NULL,
        false,
        NULL,
        'Rejected'),
        (5,
        '2024-02-20',
        true,
        'resume_05.pdf',
        true,
        'cover_letter_05.pdf',
        'Accepted');

SELECT *
FROM job_applied;